#!/bin/sh

usage() {
	echo "usage: skull [ -v | file [ -o output ] [ -- args ]]"
	exit 0
}

[ -z "$1" ] && usage

# shift params if the first argument is not an option
case "$1" in
	-*) ;;
	*) filename=$1; shift ;;
esac

while getopts ":vhcSEo:" o; do
	case "$o" in
		v)
			/bin/echo -e "\033[92mSkull\033[0m $(git describe --tags --abbrev=0)"
			exit 0
			;;
		h) usage; exit 0 ;;
		c) COMPILE=true ;;
		S) ASM=true ;;
		E) PREPRO=true ;;
		o) OUT_FILE=$OPTARG ;;
		*) echo "Unknown option \"-$OPTARG\"" ; exit 1 ;;
	esac
done

shift $(expr $OPTIND - 1)

$(dirname $0)/_skull $filename || exit 1

case "$filename" in
	*".sk") ;;
	*) exit 0 ;;
esac

base=$(dirname $filename)/.$(basename $filename)
[ -z "$OUT_FILE" ] && {
	[ -z "$ASM" ] &&
		OUT_FILE=$base.o ||
		OUT_FILE=$base.s;
}

# mimic -E option in cc (print preproccessor output to screen, in this case, LLVM IR)
[ ! -z "$PREPRO" ] &&
	cat $base.ll &&
	rm $base.ll &&
	exit 0

# mimic -S option in cc (output assembly)
file_type=obj
[ -z "$ASM" ] || file_type=asm

llc-9 $base.ll -filetype=$file_type -o $OUT_FILE || exit 1

rm $base.ll

[ -z "$ASM" ] || exit 0

# mimic -c option in cc (compile, but dont link)
[ -z "$COMPILE" ] || exit 0

cc $OUT_FILE -o "${filename%.*}" "$@" -I/usr/include/skull
rm $OUT_FILE