#!/bin/sh

stop() {
	printf "most recent command had non-zero exit code, commit aborted\n"
	exit 1
}

make TRACE=1 clean all || stop

./build/test/test || stop

cp ./skull/skull ./build/skull/skull
./test/sh/main.sh || stop

./.github/workflows/clang_tidy.sh || stop

./.github/workflows/line_len.sh || stop

cd test/docs/c-integration/
make SKULL=../../../build/skull/skull || stop
cd ../../..

printf "\nRunning shellcheck\n"

# i prefer doas, but use sudo as a backup
SUDO=$(command -v doas || command -v sudo)

$SUDO docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable \
	skull/skull test/sh/main.sh Makefile || stop
