FROM ubuntu:22.04

RUN apt update && \
	apt upgrade -y && \
	DEBIAN_FRONTEND=noninteractive apt install \
		gcc-11 \
		llvm-13-runtime -y && \
	rm -rf /var/lib/apt/lists/*

COPY --from=skull:ubuntu-dev /usr/local/bin/skull /usr/local/bin/skull
COPY --from=skull:ubuntu-dev /usr/lib/libskull.so /usr/lib/libskull.so

RUN update-alternatives --install /usr/bin/cc cc $(which gcc-11) 100

ENTRYPOINT ["skull"]
