FROM archlinux:base-devel

RUN pacman -Syu --noconfirm \
	clang \
	llvm \
	llvm-libs \
	git \
	vim

RUN sed -i "s/LLVMCreatePassBuilderOptions()/LLVMCreatePassBuilderOptions(void)/" $(llvm-config-13 --includedir || llvm-config --includedir)/llvm-c/Transforms/PassBuilder.h

WORKDIR /skull
COPY . .

RUN make DEBUG=1 options skull test e2e libskull install install-dev && \
	make clean
