FROM alpine:3.18

RUN apk update && \
	apk upgrade && \
	apk add \
		build-base \
		llvm15-libs && \
	rm /var/cache/apk/*

COPY --from=skull:alpine-dev /usr/local/bin/skull /usr/local/bin/skull
COPY --from=skull:alpine-dev /usr/lib/libskull.so /usr/lib/libskull.so

RUN ln -sf $(which clang) /usr/bin/cc

ENTRYPOINT ["skull"]
