FROM archlinux:base-devel

RUN pacman-key --init && \
	pacman -Sy --noconfirm archlinux-keyring && \
	pacman -Syu --noconfirm \
		clang \
		llvm \
		llvm-libs \
		git \
		vim

WORKDIR /skull
COPY . .

RUN make DEBUG=1 options skull test e2e libskull install install-dev && \
	make clean
