FROM alpine:3.18

RUN apk update && \
	apk upgrade && \
	apk add \
		build-base \
		clang \
		git \
		file \
		llvm15-dev && \
	rm /var/cache/apk/*

WORKDIR /skull
COPY . .

RUN make DEBUG=1 options skull test e2e libskull install install-dev && \
	make clean
