FROM ubuntu:jammy

RUN apt update && \
	apt upgrade -y && \
	DEBIAN_FRONTEND=noninteractive apt install \
		build-essential \
		gcc-11 \
		clang-15 \
		clang-tidy-15 \
		llvm-15-dev \
		shellcheck \
		git \
		file \
		xxd -y
