.TH SKULLC 1 "August 2020" "Linux" "User Manuals"
.SH NAME
skullc \- Compile a skull file
.SH SYNOPSIS
.B skullc\fR [\fB-v\fR|\fIfile\fR]
.SH DESCRIPTION
When the \fB-v\fR option is passed, print the current version. Otherwise, try and compile \fBfile\fR, which must end in ".sk". If compilation succeeds, a new binary file (with the ".sk" extension removed) will be put into the same directory as \fBfile\fR.
.SH AUTHOR
dosisod <https://github.com/dosisod>