f() Int {
	return 1
}

f()

f2(x: Int) {
	noop
}

f3(y: Int, z: Int) {
	noop
}

f4() {
	# wrapping this in a function, since variable declarations inside functions
	# are different then those outside functions (basically globals)

	mut local_var := 1

	if true {
		mut if_test := 1
	}

	mut int := 1234
	mut float := 3.1415
	mut rune := 'x'
	mut bool := false
	mut str := "some string"

	if bool {
		noop
	}
}
