name: tests

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install clang-tidy
      run: |
        sudo apt install clang-tidy
        clang-tidy --version
    - name: Run clang-tidy
      run: clang-tidy -checks=*,-llvm-header-guard src/**/*.{c,h} -- -std=c99
    - name: Setup dir
      run: mkdir build
    - name: Generate cmake files
      run: |
        cd build
        cmake --version
        cmake ..
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Run tests
      run: ./build/test/Test
    - name: Run skull parser
      run: |
        c99 -shared src/functions/libhello.c -ldl -o src/functions/libhello.so
        ./build/src/skull src/main.skull