name: tests

on: [push, pull_request]

jobs:
  clang-tidy-and-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy
      run: sudo apt install clang-tidy-10

    - name: Run clang-tidy-10
      run: |
        clang-tidy-10 --version
        ./.github/workflows/clang_tidy.sh

    - name: Run Shellcheck
      run: |
        shellcheck --version
        shellcheck test/sh/main.sh Makefile

  test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: make TRACE=1 CC=gcc-9 options clean all

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: make TRACE=1 CC=clang options clean all

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  tests-with-skull-installed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: sudo make TRACE=1 CC=gcc-9 options install install-dev

    - name: Run Skull
      run: |
        skull test/main.sk
        ./test/main

    - name: Run C integration test
      run: |
        cd test/docs/c-integration
        make
