name: tests

on: [push, pull_request]

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-tidy
      run: sudo apt install clang-tidy

    - name: Run clang-tidy
      run: |
        clang-tidy --version
        ./.github/workflows/clang_tidy.sh

    - name: Build (GCC)
      run: |
        $(which cc) -v
        make clean all

    - name: Build (Clang)
      run: |
        sudo ln -sf $(which clang) $(which cc)
        $(which cc) -v
        make clean all

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull
      run: ./build/src/skull src/main.skull

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

    - name: Install Skull
      run: sudo make install