name: tests

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install clang-tidy
      run: |
        sudo apt install clang-tidy
        clang-tidy --version
    - name: Run clang-tidy
      run: ./.github/workflows/clang_tidy.sh
    - name: Setup dir
      run: mkdir build
    - name: Build
      run: |
        make all
    - name: Run tests
      run: ./build/test/test
    - name: Run skull parser
      run: |
        c99 -shared src/functions/libhello.c -ldl -o src/functions/libhello.so
        ./build/src/skull src/main.skull