name: tests

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy
      run: sudo apt install clang-tidy-10

    - name: Run clang-tidy-10
      run: |
        clang-tidy-10 --version
        ./.github/workflows/clang_tidy.sh

  test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: |
        export CC=gcc-8
        make options clean all -e

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: |
        cp skull/skull build/skull/skull
        ./test/sh/main.sh

  test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: |
        export CC=clang
        make options clean all -e

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: |
        cp skull/skull build/skull/skull
        ./test/sh/main.sh

  tests-with-skull-installed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build
      run: sudo CC=gcc-8 make options install install-dev -e

    - name: Run Skull
      run: |
        skull test/main.sk
        ./test/main

    - name: Run C integration test
      run: |
        cd test/docs/c-integration
        make

  test-valgrind-and-precommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM 10
      run: sudo apt install llvm-10-dev

    - name: Build tests
      run: |
        export CC=gcc-8
        make options clean test -e

    - name: Install Valgrind
      run: |
        sudo apt update
        sudo apt install valgrind

    - name: Run Valgrind on tests
      run: valgrind --leak-check=full ./build/test/test

    - name: Install clang-tidy
      run: sudo apt install clang-tidy-10
