name: tests

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-tidy
      run: sudo apt install clang-tidy

    - name: Run clang-tidy
      run: |
        clang-tidy --version
        ./.github/workflows/clang_tidy.sh

  test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        $(which cc) -v
        make clean all

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        sudo ln -sf $(which clang) $(which cc)
        $(which cc) -v
        make clean all

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  test-installable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Skull
      run: |
        sudo make install
        ./test/sh/shebang.sk