name: tests

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-tidy
      run: sudo apt install clang-tidy-9

    - name: Run clang-tidy-9
      run: |
        clang-tidy-9 --version
        ./.github/workflows/clang_tidy.sh

  test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        export CC=gcc-8
        make options clean all -e

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        export CC=clang
        make options clean all -e

    - name: Run tests
      run: ./build/test/test

    - name: Run Skull unit tests
      run: ./test/sh/main.sh

  test-installable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Skull
      run: sudo CC=gcc-8 make options install -e

  test-skull-installed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: sudo CC=gcc-8 make options install -e

    - name: Run Skull
      run: |
        skull skull/main.sk
        ./skull/main

  test-precommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run pre-commit file
      run: |
        sudo ln -sf $(which gcc-8) $(which cc)
        ./pre-commit
